#!/usr/bin/env python3
"""
Generate and add acceptance criteria to issues.
"""

import os
import sys

import yaml
from github import Github  # noqa: E402 - installed in CI environment


def load_config():
    """Load Cloud Agent configuration."""
    config_path = ".github/cloud-agent-config.yml"

    if not os.path.exists(config_path):
        print(f"⚠️ Config file not found: {config_path}")
        return None

    with open(config_path) as f:
        return yaml.safe_load(f)


def generate_acceptance_criteria(issue, config):
    """Generate acceptance criteria based on issue content."""
    print(f"✅ Generating acceptance criteria for issue #{issue.number}")

    ac_config = config.get("acceptance_criteria", {})
    if not ac_config.get("enabled", False):
        print("ℹ️ Acceptance criteria generation is disabled")
        return

    # Determine issue type
    issue_labels = [label.name for label in issue.labels]
    is_feature = "feature" in issue_labels
    is_refactor = "refactor" in issue_labels
    is_bug = "bug" in issue_labels

    # Generate criteria based on rules
    generation_rules = ac_config.get("generation_rules", {})

    # Functional requirements
    functional_requirements = []
    if is_feature:
        functional_requirements = [
            "User can access the new feature through the bot interface",
            "Feature behaves correctly under normal conditions",
            "Feature handles edge cases gracefully",
            "User receives appropriate feedback on actions",
        ]
    elif is_bug:
        functional_requirements = [
            "Bug is completely resolved",
            "System behaves as originally intended",
            "No regression in related functionality",
        ]
    elif is_refactor:
        functional_requirements = [
            "All existing functionality continues to work",
            "No breaking changes introduced",
            "Code behavior remains consistent",
        ]

    # Technical requirements
    technical_requirements = [
        "Code follows project style guide (passes `ruff check`)",
        "No linting errors in modified files",
        "Performance impact is minimal or positive",
        "Security best practices are followed",
        "No secrets or tokens committed to git",
    ]

    # Testing requirements
    testing_requirements = [
        "New functionality is covered by tests (if applicable)",
        "All existing tests pass",
        "Manual testing completed and documented",
        "Edge cases are tested",
    ]

    # Documentation requirements
    documentation_requirements = [
        "README.md updated if user-facing changes exist",
        "Code comments added for complex logic",
        "CHANGELOG entry added (if applicable)",
        "Documentation reflects actual implementation",
    ]

    # Build comment
    comment = "## ✅ Acceptance Criteria\n\n"
    comment += "_Generated by Cloud Agent - feel free to edit as needed_\n\n"

    comment += "### 🎯 Functional Requirements\n\n"
    for req in functional_requirements:
        comment += f"- [ ] {req}\n"

    comment += "\n### 🔧 Technical Requirements\n\n"
    for req in technical_requirements:
        comment += f"- [ ] {req}\n"

    comment += "\n### 🧪 Testing Requirements\n\n"
    for req in testing_requirements:
        comment += f"- [ ] {req}\n"

    comment += "\n### 📚 Documentation Requirements\n\n"
    for req in documentation_requirements:
        comment += f"- [ ] {req}\n"

    comment += "\n---\n\n"
    comment += "_Use checkboxes above to track progress_\n"
    comment += "_Use `/estimate` to get time estimate_"

    # Post comment
    issue.create_comment(comment)
    print("✅ Acceptance criteria added to issue")


def main():
    """Main execution."""
    github_token = os.getenv("GITHUB_TOKEN")
    issue_number = os.getenv("ISSUE_NUMBER")

    if not github_token:
        print("❌ GITHUB_TOKEN not set")
        sys.exit(1)

    if not issue_number:
        print("❌ ISSUE_NUMBER not set")
        sys.exit(1)

    # Load configuration
    config = load_config()
    if not config:
        sys.exit(1)

    # Get GitHub objects
    g = Github(github_token)
    repo = g.get_repo(os.getenv("GITHUB_REPOSITORY"))
    issue = repo.get_issue(int(issue_number))

    # Generate and add criteria
    generate_acceptance_criteria(issue, config)


if __name__ == "__main__":
    main()
