#!/usr/bin/env python3
"""
Generate subtasks for complex issues.
"""

import os
import sys

import yaml
from github import Github  # noqa: E402 - installed in CI environment


def load_config():
    """Load Cloud Agent configuration."""
    config_path = ".github/cloud-agent-config.yml"

    if not os.path.exists(config_path):
        print(f"⚠️ Config file not found: {config_path}")
        return None

    with open(config_path) as f:
        return yaml.safe_load(f)


def generate_subtasks(issue, config):
    """Generate subtasks based on issue type and content."""
    print(f"🔄 Generating subtasks for issue #{issue.number}")

    subtask_config = config.get("issue_creation", {}).get("subtask_generation", {})
    if not subtask_config.get("enabled", False):
        print("ℹ️ Subtask generation is disabled")
        return

    # Determine issue type
    issue_labels = [label.name for label in issue.labels]
    issue_type = None

    for label in issue_labels:
        if label in ["feature", "bug", "refactor", "docs"]:
            issue_type = label
            break

    if not issue_type:
        issue_type = "feature"  # Default

    # Get breakdown rules
    breakdown_rules = subtask_config.get("breakdown_rules", [])
    split_by = []

    for rule in breakdown_rules:
        if rule.get("type") == issue_type:
            split_by = rule.get("split_by", [])
            break

    if not split_by:
        print(f"⚠️ No breakdown rules for type: {issue_type}")
        return

    # Create subtasks
    subtasks_created = []

    for i, phase in enumerate(split_by, 1):
        subtask_title = f"[Subtask {i}/{len(split_by)}] {phase.title()}: {issue.title}"

        subtask_body = f"""
## 📋 Subtask Details

**Parent Issue**: #{issue.number}
**Phase**: {phase.title()}
**Order**: {i} of {len(split_by)}

---

### 🎯 Objective
{get_phase_objective(issue_type, phase)}

### 📝 Related to
{issue.body[:200] if issue.body else "See parent issue for details"}...

---

_This subtask was automatically generated by Cloud Agent_
_Use `/accept` to generate acceptance criteria_
"""

        # Create subtask issue
        subtask = issue.repository.create_issue(
            title=subtask_title, body=subtask_body, labels=issue_labels + ["subtask"]
        )

        subtasks_created.append(subtask)
        print(f"✅ Created subtask #{subtask.number}: {phase}")

    # Add comment to parent issue
    if subtasks_created:
        comment = "🤖 **Cloud Agent - Subtasks Generated**\n\n"
        comment += "This issue has been broken down into the following subtasks:\n\n"

        for subtask in subtasks_created:
            comment += f"- [ ] #{subtask.number} - {subtask.title}\n"

        comment += f"\n✅ Total: {len(subtasks_created)} subtasks created\n"
        comment += "\n_Track progress by checking off completed subtasks above_"

        issue.create_comment(comment)
        print(f"✅ Created {len(subtasks_created)} subtasks")


def get_phase_objective(issue_type, phase):
    """Get objective description for a phase."""
    objectives = {
        "feature": {
            "frontend": "Implement user interface components and user interactions",
            "backend": "Implement server-side logic, APIs, and data processing",
            "testing": "Write and execute tests to verify functionality",
            "documentation": "Update documentation, README, and code comments",
        },
        "bug": {
            "reproduce": "Reproduce the bug and document exact steps",
            "fix": "Implement the fix and verify it resolves the issue",
            "test": "Add tests to prevent regression",
            "verify": "Verify fix in production-like environment",
        },
        "refactor": {
            "analysis": "Analyze current code and identify areas for improvement",
            "implementation": "Refactor code following best practices",
            "testing": "Ensure all existing tests still pass",
            "cleanup": "Remove old code and update documentation",
        },
        "docs": {
            "research": "Research and gather information",
            "writing": "Write comprehensive documentation",
            "review": "Review and edit for clarity",
            "publish": "Publish and notify relevant stakeholders",
        },
    }

    return objectives.get(issue_type, {}).get(phase, f"Complete {phase} phase")


def main():
    """Main execution."""
    github_token = os.getenv("GITHUB_TOKEN")
    issue_number = os.getenv("ISSUE_NUMBER")

    if not github_token:
        print("❌ GITHUB_TOKEN not set")
        sys.exit(1)

    if not issue_number:
        print("❌ ISSUE_NUMBER not set")
        sys.exit(1)

    # Load configuration
    config = load_config()
    if not config:
        sys.exit(1)

    # Get GitHub objects
    g = Github(github_token)
    repo = g.get_repo(os.getenv("GITHUB_REPOSITORY"))
    issue = repo.get_issue(int(issue_number))

    # Generate subtasks
    generate_subtasks(issue, config)


if __name__ == "__main__":
    main()
